source 'https://rubygems.org'

# Public gems from RubyGems:
gem 'activesupport', '~> 8.1.3'
gem 'bundler-audit', '~> 0.9', require: false
gem 'chutney', '~> 3.12', require: false
gem 'config', '~> 5.6'
gem 'cucumber', '~> 10.0'
gem 'dvla-atlas', '~> 1.1'
gem 'dvla-herodotus', '~> 2.1'
gem 'dvla-lint', '~> 1.10', require: false
gem 'faker', '~> 3.5'
gem 'faker_maker', '~> 3.0'
gem 'hash_miner', '~> 1.1'
gem 'httparty', '~> 0.23'
gem 'irb'
gem 'parallel_tests', '~> 5.3', require: false
gem 'rack', '~> 3.2.6'
gem 'rake', '~> 13.3'
gem 'rspec-expectations', '~> 3.13'
gem 'simple_symbolize', '~> 4.0'
